#!/bin/sh -e
TOPDIR=`pwd`
NUMPROC=8
if [ $# -ge 1 ]
then
    NUMPROC=$1
    if [ $# -ge 2 ]
    then
        TOPDIR=$2
    fi
fi

if [ ! -e $TOPDIR/Build_And_Install_Trilinos ]
then
    echo "Cannot find Build_And_Install_Trilinos in $TOPDIR.  Please either"
    echo "run this script from the directory in which it exists, or provide"
    echo "the path to your XyceBundle clone as the first argument."
    exit 1
fi

UNAME=`uname`
# Cygwin has a version number in there that seems to be related more to
# the Windows version than to Cygwin.  Just use CYGWIN_NT
set +e
echo $UNAME | grep CYGWIN_NT > /dev/null
if [ $? = 0 ]
then
    UNAME="CYGWIN_NT"
fi
set -e

echo "This script will try to build and test Xyce for your system,"
echo "which uname reports as "${UNAME}

echo "Script is set up to use $NUMPROC cores."
echo "Press Control-C if this is more than your system has and edit NUMPROC or"
echo "invoke this script again with a numeric argument to say how many cores to use"
read -p "or hit ENTER to continue with the installation." FOOBAR


if [ ! -e $TOPDIR/XyceLibs/${UNAME}_serial ]
then
   echo "Cannot find directory of Trilinos libraries.  Building those."
   $TOPDIR/Build_And_Install_Trilinos $NUMPROC $TOPDIR
fi

# Always bootstrap.  Something might have changed
    SAVEDIR=`pwd`
    cd $TOPDIR/Xyce
    ./bootstrap
    cd $SAVEDIR
    echo "Bootstrap done."


if [ -x $TOPDIR/xyce_reconfigures/reconfigure.xyce.${UNAME}_serial ]
then
    mkdir -p Xyce_Builddir_${UNAME}_serial
    cd Xyce_Builddir_${UNAME}_serial
    $TOPDIR/xyce_reconfigures/reconfigure.xyce.${UNAME}_serial $TOPDIR
    make -j${NUMPROC}
    EXECUTABLE=`pwd`/src/Xyce
    eval `$TOPDIR/Xyce_Regression/TestScripts/suggestXyceTagList.sh "$EXECUTABLE"`
    echo "Testing Xyce with taglist ${TAGLIST}"
    $TOPDIR/Xyce_Regression/TestScripts/run_xyce_regressionMP \
        --numproc=${NUMPROC} \
        --output=`pwd`/Xyce_Test --xyce_test=$TOPDIR/Xyce_Regression \
        --taglist="$TAGLIST" \
        $EXECUTABLE
else
    echo "No reconfigure.xyce."${UNAME}"_serial  was found."
    echo "Please copy $TOPDIR/xyce_reconfigures/reconfigure.xyce.sample to $TOPDIR/xyce_reconfigures/reconfigure.xyce."${UNAME}"_serial"
    echo ", customize it, make it executable with "
    echo "        chmod u+x  $TOPDIR/xyce_reconfigures/reconfigure.xyce."${UNAME}"_serial"
    echo "and try again."
fi
