#!/bin/sh -e
TOPDIR=`pwd`
NUMPROC=8
PARALLEL_OPT=""
s_or_p="serial"
S_OR_P="Serial"

if [ $# -ge 1 -a $1 = "--parallel" ]
then
    PARALLEL_OPT=$1
    s_or_p="parallel"
    S_OR_P="Parallel"
    shift
fi

if [ $# -ge 1 ]
then
    NUMPROC=$1
    if [ $# -ge 2 ]
    then
        TOPDIR=$2
    fi
fi

echo "PARALLEL_OPT: ${PARALLEL_OPT}"
echo "Serial or Parallel: ${S_OR_P}"
echo "NUMPROC: ${NUMPROC}"
echo "TOPDIR: ${TOPDIR}"

if [ ! -e $TOPDIR/Build_And_Install_Trilinos ]
then
    echo "Cannot find Build_And_Install_Trilinos in $TOPDIR.  Please either"
    echo "run this script from the directory in which it exists, or run this"
    echo "script with two arguments, with the number of cores to use as the"
    echo "first argument and the path to your XyceBundle clone as the second"
    echo "argument."
    exit 1
fi

UNAME=`uname`
XTRATAGS=""
# Cygwin has a version number in there that seems to be related more to
# the Windows version than to Cygwin.  Just use CYGWIN_NT
set +e
echo $UNAME | grep CYGWIN_NT > /dev/null
if [ $? = 0 ]
then
    UNAME="CYGWIN_NT"
    XTRATAGS="-scipy"
fi
set -e

echo "This script will try to build and test Xyce for your system,"
echo "which uname reports as "${UNAME}

echo "Script is set up to use $NUMPROC cores."
echo "Press Control-C if this is more than your system has and edit NUMPROC or"
echo "invoke this script again with a numeric argument to say how many cores to use"
read -p "or hit ENTER to continue with the installation." FOOBAR

MPIRUN="mpirun"
if [ ${UNAME} = "FreeBSD" ]
then
    MPIRUN="/usr/local/mpi/openmpi/bin/mpirun"
fi

if [ ! -e $TOPDIR/XyceLibs/${UNAME}_${s_or_p} ]
then
   echo "Cannot find directory of Trilinos libraries.  Building those."
   $TOPDIR/Build_And_Install_Trilinos ${PARALLEL_OPT} $NUMPROC $TOPDIR
fi

# Always bootstrap.  Something might have changed
    SAVEDIR=`pwd`
    cd $TOPDIR/Xyce
    ./bootstrap
    cd $SAVEDIR
    echo "Bootstrap done."


if [ -x $TOPDIR/xyce_reconfigures/reconfigure.xyce.${UNAME}_${s_or_p} ]
then
    mkdir -p Xyce_Builddir_${UNAME}_${s_or_p}
    cd Xyce_Builddir_${UNAME}_${s_or_p}
    $TOPDIR/xyce_reconfigures/reconfigure.xyce.${UNAME}_${s_or_p} $TOPDIR
    make -j${NUMPROC}
    EXECUTABLE=`pwd`/src/Xyce
    XYCECMD=$EXECUTABLE
    eval `$TOPDIR/Xyce_Regression/TestScripts/suggestXyceTagList.sh "$EXECUTABLE"`
    if [ "${s_or_p}" = "parallel" ]
    then
	XYCECMD="${MPIRUN} -np 2 --bind-to none $EXECUTABLE"
	NUMPROC=`echo $NUMPROC/2 | bc`
    fi
    echo "Testing ${s_or_p} Xyce in groups of ${NUMPROC} with taglist ${TAGLIST}${XTRATAGS}"
    $TOPDIR/Xyce_Regression/TestScripts/run_xyce_regressionMP \
        --numproc=${NUMPROC} \
        --output=`pwd`/Xyce_Test --xyce_test=$TOPDIR/Xyce_Regression \
        --resultfile=`pwd`/regr_results_all \
        --taglist="${TAGLIST}${XTRATAGS}" \
        "$XYCECMD"
else
    echo "No reconfigure.xyce."${UNAME}"_${s_or_p}  was found."
    echo "Please copy $TOPDIR/xyce_reconfigures/reconfigure.xyce.sample to $TOPDIR/xyce_reconfigures/reconfigure.xyce."${UNAME}"_${s_or_p}"
    echo ", customize it, make it executable with "
    echo "        chmod u+x  $TOPDIR/xyce_reconfigures/reconfigure.xyce."${UNAME}"_${s_or_p}"
    echo "and try again."
fi
