#!/bin/sh -e

if [ $# -ge 1 ]
then
    TOPDIR=$1
else
    TOPDIR=`pwd`
fi

if [ ! -e $TOPDIR/Build_And_Install_Trilinos ]
then
    echo "Cannot find Build_And_Install_Trilinos in $TOPDIR.  Please either"
    echo "run this script from the directory in which it exists, or provide"
    echo "the path to your XyceBundle clone as the first argument."
    exit 1
fi

echo "This script will try to build and install Trilinos for your system,"
echo "which uname reports as "`uname`

NUMPROC=8

read -p "Script is set up to use $NUMPROC cores.  Control-C if this is more than your system has and edit NUMPROC to something smaller.  Hit ENTER to continue with this " FOOBAR

if [ -x $TOPDIR/trilinos_reconfigures/reconfigure.trilinos.`uname`_serial ]
then
    mkdir -p Trilinos_Builddir_`uname`
    cd Trilinos_Builddir_`uname`
    $TOPDIR/trilinos_reconfigures/reconfigure.trilinos.`uname`_serial $TOPDIR
    make -j${NUMPROC}
    make install
else
    echo "No reconfigure.trilinos."`uname`"_serial  was found."
    echo "Please copy reconfigure.trilinos.sample to reconfigure.trilinos."`uname`"_serial"
    echo ", customize it, make it executable with "
    echo "        chmod u+x  reconfigure.trilinos."`uname`"_serial"
    echo "and try again."
fi
